ModelTraining/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import bigdelete
app_name = "ModelTraining"
urlpatterns = [
    path('', views.Home, name = 'Home'),
    path('Login/delete/<int:id>', views.bigdelete, name="bigdelete"),
    path('Signup/',views.Signup, name = 'Signup'),
    path('Login/',views.Login, name = 'Login'),
    path('Books/',views.Books,name = "Books"),
    path('Blogpost/',views.Blog, name = "Blog"),
]

Story5/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ModelTraining.urls')),
    path('login/',auth_views.LoginView.as_view(template_name = "loginn.html"), name = "login"),
    path('logout/',auth_views.LogoutView.as_view(template_name ="logout.html"),name = "logout"),
    path('regis',include('authx.urls'))
]

authx/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "authx"
urlpatterns = [
    path('', views.register, name = 'register'),
    path('login/',views.login,name = "login"),
    path('logout/',views.logout,name = "logout")

]

ModelTraining/models.py
from django.db import models
import datetime
import pytz
import Story5.settings

class CForm(models.Model):
    id = models.AutoField(primary_key = True)
    aktivitas = models.CharField(max_length = 100)
    tanggal = models.DateField(null = True)
    jam = models.TimeField(null = True)
    tempat = models.CharField(max_length =200)
    kategori = models.CharField(max_length =200)
    
# Create your models here.

authx/models.py
from django.db import models

# Create your models here.

ModelTraining/forms.py
from django import forms
from .models import CForm
from django import forms
from ModelTraining import models
from django.utils import timezone
class ContactForm(forms.Form):
    event_attrs = { 
        "type":"text",
        "placeholder":"Event Name",
        "name":"event",
        "value":"",
    }
    calendar_attrs = {
        "type":"date",
        "name":"tanggal",
        "value":"",
    }

    time_attrs = {
        "type":"time",
        "name":"jam",
        "value":"",
    }
    aktivitas = forms.CharField(label =" Masukan Aktivitas Anda", max_length = 100)
    tanggal = forms.DateField(initial=timezone.now, required = True, widget=forms.DateInput(attrs=calendar_attrs))
    jam = forms.TimeField(initial=timezone.now, required=True,widget=forms.TimeInput(attrs=time_attrs))
    tempat = forms.CharField(label =" Masukan Tempat Aktivitas Anda", max_length = 100)
    kategori = forms.CharField(label =" Masukan Kategori Aktivitas Anda", max_length = 100)

ModelTraining/views.py
from django.shortcuts import render
from .forms import ContactForm
from .models import CForm
from django.views.generic import DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,get_object_or_404
from .forms import ContactForm
from django.urls import reverse
from django.http import HttpResponseRedirect
# Create your views here.
def Home(request):
    return render(request, 'index.html')
def Signup(request):
    form = ContactForm()
    if request.method == 'POST':
        print('test')
        cform = CForm(aktivitas = request.POST.get('aktivitas'),
        jam = request.POST.get('jam'),
        tanggal = request.POST.get('tanggal'),
        tempat = request.POST.get('tempat'),
        kategori = request.POST.get('kategori')
        )
        cform.save()
    else:
        form = ContactForm()
    return render(request, 'Signup.html',{'form' : form})
def Login(request):
    Arguement = {
    'showSched' : CForm.objects.all(),
    'schedules' : ContactForm
  }
    return render(request, 'Success.html', Arguement )

def bigdelete(request, id):
    deletion = get_object_or_404(CForm, pk=id)
    deletion.delete()
    return HttpResponseRedirect(reverse('ModelTraining:Login'))
def Books(request):
    return render(request,"Books.html")
def Blog(request):
    return render(request,"blog.html")

    

authx/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import views as auth_views
# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account Successfully created for {username}.")
            return redirect("/login/")
    else:
        form = UserCreationForm()
    return render(request,'indexauth.html',{'form' : form})
    
def login(request):
    return render(request,"loginn.html")
def logout(request):
    return render(request,"logout.html")

ModelTraining/templates/Books.html
{% load static %}
<html>
<head>
    <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
    <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/book.css' %}" id = "tema">
    <script src="{% static 'scripts/books.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Home"%}'>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Signup" %}'>Add Activity</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Login" %}'> Activity List</a>
                    </li>
                    <li>
                        <a class = "nav-link"> Bookfinding</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Blog"%}'> Blog</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class = "nav-link"  href='{%url "logout"%}'> Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a class = "nav-link"  href ='{%url "login" %}'> Login</a>
                    </li>
                    {% endif %}
                </ul>
        </div>
    </nav>
    <h2> Bookfinder</h2>
    <div class='searchbar' style="width: 20rem;">
        <div class="input-group mb-3">

            <input type="text" class="form-control" id="search-query" placeholder="Search book tile or keywords">
            <div class="input-group-prepend">
                <button class="btn btn-outline-secondary" type="submit" onclick="getQuery()" id="button-addon1">Search</button>
            </div>
        </div>
    </div>
    <div class="shelf" style="margin: auto;height: 100%;width: 100%;">
        <table id="book" class="table table-hover table-responsive table-da rk" style="margin: auto;">
            <thread>
                <tr>
                    <th scope="col">Cover</th>
                    <th scope="col">Title</th>
                    <th scope="col">Author</th>
                    <th scope="col">Publisher</th>
                </tr>
            </thread>
        </table>
    </div>
</body>
</html>

ModelTraining/templates/Login.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title> Log In</title>
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
        <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
        <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}" id = "tema">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Home"%}'>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Signup" %}'>Add Activity</a>
                    </li>
                    <li>
                        <a class = "nav-link"> Activity List</a>
                    </li>
                    <li>
                        <a class = "nav-link"  href='{%url "ModelTraining:Books"%}'> Bookfinding</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Blog"%}'> Blog</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class = "nav-link"  href='{%url "logout"%}'> Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a class = "nav-link"  href ='{%url "login" %}'> Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </body>
</html>

ModelTraining/templates/Signup.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
        <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
        <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}" id = "tema">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    </head>
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Home"%}'>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link">Add Activity</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Login" %}'> Activity List</a>
                    </li>
                    <li>
                        <a class = "nav-link"  href='{%url "ModelTraining:Books"%}'> Bookfinding</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Blog"%}'> Blog</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class = "nav-link"  href='{%url "logout"%}'> Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a class = "nav-link"  href ='{%url "login" %}'> Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class = 'forms'>
            <form method = 'POST'>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                {% csrf_token %}
                {{form}}
                <button type = 'submit'> Submit</button>
            </form>
        </div>


    </body>
</html>

ModelTraining/templates/Success.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title> Log In</title>
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
    <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" id = "tema">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href='{%url "ModelTraining:Home"%}'>Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href='{%url "ModelTraining:Signup" %}'>Add Activity</a>
                </li>
                <li>
                    <a class = "nav-link"> Activity List</a>
                </li>
                <li>
                    <a class = "nav-link"  href='{%url "ModelTraining:Books"%}'> Bookfinding</a>
                </li>
                <li>
                    <a class = "nav-link" href='{%url "ModelTraining:Blog"%}'> Blog</a>
                </li>
                {% if user.is_authenticated %}
                <li>
                    <a class = "nav-link"  href='{%url "logout"%}'> Logout</a>
                </li>
                {% else %}
                <li>
                    <a class = "nav-link"  href ='{%url "login" %}'> Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
          {%for items in showSched%}
          <div class="card text-center" style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Aktivitas: {{items.aktivitas}}, Tempat:{{items.tempat}}</h5>
              <p class="card-text">Waktu:{{items.jam}}, Tanggal:{{items.tanggal}} <p> Kategori : {{items.kategori}}</p></p>
              <a href="{% url 'ModelTraining:bigdelete' items.id %}" class="btn btn-primary">delete</a>
            </div>
          </div>
          {%endfor%}
    </body>
</html>

ModelTraining/templates/blog.html
{% load static %}
<html>
<head>
    <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
    <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/book.css' %}" id = "tema">
    <script src="{% static 'scripts/books.js' %}"></script>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Home"%}'>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Signup" %}'>Add Activity</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Login" %}'> Activity List</a>
                    </li>
                    <li>
                        <a class = "nav-link"  href='{%url "ModelTraining:Books"%}'> Bookfinding</a>
                    </li>
                    <li>
                        <a class = "nav-link"> Blog</a>
                    </li>
                
                {% if user.is_authenticated %}
                    <li>
                        <a class = "nav-link"  href='{%url "logout"%}'> Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a class = "nav-link"  href ='{%url "login" %}'> Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
<h2>Pengalaman saya</h3>
<h5>Load balancer pertama saya dibuat dengan <b> nginx.</b> Saya baca banyak hal tentang nginx dan cara menginstall nya. Ternyata cukup mudah cara menginstall nginx, cukup mendownload dan mengekstrak, lalu run nginx.exe.</h5>
<h5>
    Saya membuat configuration file saya sendiri yang saya include di nginx.conf.
    Pertama tama saya bingung cara mengecek apakah nginx sudah jalan atau belum. Saya run nginx dan membuka localhost, dan sudah ada
    halaman konfirmasi nginx yang menandakan dia telah di run. Namun saya tidak tahu cara mengecek apakah aplikasi django saya sudah menggunakan nya.
</h5>
<h5>
    Setelah membaca baca lagi tentang nginx.exe, dan bertanya teman teman, saya mempunyai rencana untuk mengetest nginx saya. Jika nginx.exe telah berjalan dengan konfigurasi yang saya tetapkan,
    maka harusnya sudah ada load balancing basic yang terjadi. Dengan load balancing tersebut, jika saya nyalakan aplikasi saya di 2 port yang berbeda, dan mematikan 1 port, maka harusnya secara automatis akan di realokasikan ke port yang masih berjalan.
    Untuk mengetest ini, saya run aplikasi django saya. Lalu, saya membuka cmd baru dan me run aplikasi yang sama di port yang berbeda. Saat saya mematikan cmd pertama dan memasukan alamat localhost, aplikasi saya masih berjalan. Ini berarti aplikasi saya di realokasikan ke port yang masih saya jalankan dan menandakan load balancing saya bekerja.
</h5>

ModelTraining/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title> Welcome</title>
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
        <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
        <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}" id = "tema">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Signup" %}'>Add Activity</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Login" %}'> Activity List</a>
                    </li>
                    <li>
                        <a class = "nav-link"  href='{%url "ModelTraining:Books"%}'> Bookfinding</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Blog"%}'> Blog</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class = "nav-link"  href='{%url "logout"%}'> Logout</a>
                    </li>
                    {% else %}
                    <li>
                        <a class = "nav-link"  href ='{%url "login" %}'> Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class = "regulator">
            <div id = "panels">
                <h3>Activities</h3>
                <div>
                    <p> - Doing normal things a computer science major would do<br/>
                        - Participating in social endeavours<br/>
                        - Doing a variety of hobbies</p>
                </div>

                <h3>Organizational/Commitee experiences</h3>
                <p> -Staff of Computers Get Together 2018, Equipment division<br/>
                    -Staff of COMPFEST 2018, Editorial Marketing division <br/>
                    -VPIC of COMPFEST 2019's Editorial Marketing division <br/></p>
                <h3> Achievements</h3>
                <p> None.</p>
            </div>
        </div>
        <button id = "theme_changer"> Theme Change</button>
        <div class = "greeting" align = "center">
        {% if request.user.is_authenticated %}
        <h2 class = "display-4 text-dark"> Hello, {{ request.user }} </h2>
        {% else %}
        <h2 class = "display-4 text-dark"> You are not logged in.</h2>
        {% endif %}
        </div>
    </body> 
    <script>
        $("#panels").accordion({
            collapsible:true,
            event:"click",
        });
        $('#theme_changer').click(function (){
            // console.log("test");
            // var csshref = $("body").css("background-image");
            // if(csshref == "url('static/images/Paris.jpg')"){ 
            //     $("body").css("background-image", "url('static/css/static/images/darkmode.jpg')");
            // }
            // else{
            //     $("body").css("background-image" , "url('static/css/static/images/Paris.jpg')");
            // }

            var csshref = $("#tema").attr('href');
            if(csshref == "{% static 'css/main.css' %}" ){
                $("#tema").attr('href',"{% static 'css/dark.css' %}" );
            }
            else if(csshref == "{% static 'css/dark.css' %}") {
                $("#tema").attr('href',"{% static 'css/main.css' %}" );
            }
        });
    </script>
</html>

authx/templates/indexauth.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title> Welcome</title>
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
        <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
        <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}" id = "tema">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Home"%}'>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Signup" %}'>Add Activity</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Login" %}'> Activity List</a>
                    </li>
                        <a class = "nav-link"  href='{%url "ModelTraining:Books"%}'> Bookfinding</a>
                </ul>
            </div>
        </nav>

        <div class = "content-section"></div>
            <form method = "POST">
                {% csrf_token %}
                <fieldset class = "form-group">
                    <legend class = "border-bottom mb-4"> Register</legend>
                    {{form.as_p}}
                    <div class = "form-group">
                        <button class = "btn btn-outline-info" type = "submit">Sign Up</button>
                    </div>
                    <div class = "border-top pt-3">
                        <small class="text-muted">
                            Already Have an Account? <a class = "ml-2" href ='{%url "login" %}'>click here.</a> 
                        </small>
                    </div>
                </fieldset>
            </form>
    </body> 
</html>

authx/templates/loginn.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title> Welcome</title>
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
        <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
        <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}" id = "tema">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Home"%}'>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Signup" %}'>Add Activity</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Login" %}'> Activity List</a>
                    </li>
                        <a class = "nav-link"  href='{%url "ModelTraining:Books"%}'> Bookfinding</a>
                        {% if user.is_authenticated %}
                        <li>
                            <a class = "nav-link"  href='{%url "authx:logout"%}'> Logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a class = "nav-link"  href ='{%url "login" %}'> Login</a>
                        </li>
                        {% endif %}
                </ul>
            </div>
        </nav>

        <div class = "content-section"></div>
            <form method = "POST">
                {% csrf_token %}
                <fieldset class = "form-group">
                    <legend class = "border-bottom mb-4"> Log In</legend>
                    {{form.as_p}}
                    <div class = "form-group">
                        <button class = "btn btn-outline-info" type = "submit">Log In</button>
                    </div>
                    <div class = "border-top pt-3">
                        <small class="text-muted">
                            Don't Have an Account? <a class = "ml-2" href ='{%url "authx:register" %}'>click here.</a> 
                        </small>
                    </div>
                </fieldset>
            </form>
    </body> 
</html>

authx/templates/logout.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title> Welcome</title>
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
        <script src="{% static 'scripts/jquery.js' %}" type = "text/javascript"></script>
        <script src="{% static 'scripts/jquery-ui.js' %}" type = "text/javascript"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" ntegrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/main.css' %}" id = "tema">
        <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary">
            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Home"%}'>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href='{%url "ModelTraining:Signup" %}'>Add Activity</a>
                    </li>
                    <li>
                        <a class = "nav-link" href='{%url "ModelTraining:Login" %}'> Activity List</a>
                    </li>
                        <a class = "nav-link"  href='{%url "ModelTraining:Books"%}'> Bookfinding</a>
                        {% if user.is_authenticated %}
                        <li>
                            <a class = "nav-link"  href='{%url "logout"%}'> Logout</a>
                        </li>
                        {% else %}
                        <li>
                            <a class = "nav-link"  href ='{%url "login" %}'> Login</a>
                        </li>
                        {% endif %}
                </ul>
            </div>
        </nav>

     <h2> You've been logged out.</h2>
     <div class = "border-top pt-3">
        <small class="text-muted">
         <a class = "ml-2" href ='{%url "login" %}'>Log in</a> 
        </small>
    </div>
    </body> 
</html>